# Generated by Django 5.2.8 on 2025-12-02 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_alter_provider_category_alter_provider_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('accepted', 'Accepté'), ('refused', 'Refusé'), ('cancelled', 'Annulé')], default='pending', max_length=10),
        ),
    ]
