# Generated by Django 6.0.1 on 2026-02-13 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_alter_appointment_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('accepted', 'Accepte'), ('refused', 'Refuse'), ('cancelled', 'Annule'), ('done', 'Termine')], default='pending', max_length=10),
        ),
    ]
